import { motion } from 'framer-motion';
import { Sparkles, Code2, Stethoscope, Zap, Shield, TrendingUp } from 'lucide-react';

export function Overview() {
  const highlights = [
    {
      icon: Sparkles,
      title: 'Multi-Agent Development',
      description: '92%+ code generated by Opus 4.6 Agent Teams — specialized agents for code, test, security, and FHIR working in parallel'
    },
    {
      icon: Zap,
      title: 'Rapid Deployment',
      description: 'From clinical insight to production application in 2-6 weeks with Agent Team orchestration'
    },
    {
      icon: Shield,
      title: 'Claude for Healthcare Native',
      description: 'Native CMS, ICD-10, and PubMed integrations with HIPAA-compliant prior authorization workflows'
    },
    {
      icon: TrendingUp,
      title: 'Proven ROI',
      description: '$3.70 return per $1 invested in AI-assisted development, validated across 5+ production applications'
    },
    {
      icon: Stethoscope,
      title: 'Clinician-Led, Human-in-the-Loop',
      description: 'Built by physicians who understand workflows — with EU AI Act compliant mandatory review gates at every phase'
    },
    {
      icon: Code2,
      title: 'Production Quality at Scale',
      description: '5+ production apps, 97M+ MCP SDK downloads/mo — enterprise-grade with professional testing and monitoring'
    }
  ];

  return (
    <section id="overview" className="py-20 bg-white scroll-mt-16">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header with Mount Sinai Logo */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <div className="flex justify-center mb-8">
            <img
              src="/mount-sinai-logo-production.png"
              alt="Mount Sinai Health System"
              className="h-20 w-auto"
            />
          </div>
          <h2 className="text-4xl md:text-5xl font-bold text-sinai-navy mb-4">
            The Agentic Laboratory
          </h2>
          <p className="text-xl text-gray-700 mb-2">
            Mount Sinai West Hospital
          </p>
          <p className="text-lg text-sinai-cyan font-semibold">
            Where Clinicians Lead Multi-Agent AI Development
          </p>
        </motion.div>

        {/* Mission Statement */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="max-w-4xl mx-auto mb-16"
        >
          <div className="bg-gradient-to-r from-sinai-cyan/10 to-sinai-magenta/10 rounded-2xl p-8 border-l-4 border-sinai-cyan">
            <h3 className="text-2xl font-bold text-sinai-navy mb-4">Our Mission</h3>
            <p className="text-lg text-gray-700 leading-relaxed mb-4">
              The Agentic Laboratory represents the next frontier in healthcare software development. We harness multi-agent systems — Claude Opus 4.6 Agent Teams orchestrating specialized code, test, security, and FHIR agents — to empower physicians to build production-grade applications. With Claude for Healthcare providing native CMS, ICD-10, and PubMed integrations, and the MCP ecosystem enabling 40-60% faster deployment, we deliver HIPAA-compliant solutions that perfectly match clinical workflows.
            </p>
            <p className="text-lg text-gray-700 leading-relaxed">
              As Gartner reports a 1,445% surge in multi-agent AI inquiries and 87% of Fortune 500 companies adopt AI development tools, the Agentic Laboratory leads the healthcare sector — achieving 92% AI-assisted code generation while maintaining mandatory human-in-the-loop review at every phase.
            </p>
          </div>
        </motion.div>

        {/* The Problem */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="mb-16"
        >
          <h3 className="text-3xl font-bold text-sinai-navy mb-8 text-center">The Healthcare Software Problem</h3>
          <div className="grid md:grid-cols-2 gap-8">
            <div className="bg-red-50 rounded-2xl p-6 border-l-4 border-red-500">
              <h4 className="text-xl font-bold text-red-900 mb-3">Traditional Approach</h4>
              <ul className="space-y-2 text-gray-700">
                <li className="flex items-start">
                  <span className="text-red-500 mr-2">✗</span>
                  <span>6-12 month development cycles</span>
                </li>
                <li className="flex items-start">
                  <span className="text-red-500 mr-2">✗</span>
                  <span>$200k-500k+ per application</span>
                </li>
                <li className="flex items-start">
                  <span className="text-red-500 mr-2">✗</span>
                  <span>Misaligned with clinical workflows</span>
                </li>
                <li className="flex items-start">
                  <span className="text-red-500 mr-2">✗</span>
                  <span>Requires large IT teams</span>
                </li>
                <li className="flex items-start">
                  <span className="text-red-500 mr-2">✗</span>
                  <span>Slow to adapt to changing needs</span>
                </li>
              </ul>
            </div>
            <div className="bg-green-50 rounded-2xl p-6 border-l-4 border-green-500">
              <h4 className="text-xl font-bold text-green-900 mb-3">Agentic Laboratory</h4>
              <ul className="space-y-2 text-gray-700">
                <li className="flex items-start">
                  <span className="text-green-500 mr-2">✓</span>
                  <span>2-6 week development cycles</span>
                </li>
                <li className="flex items-start">
                  <span className="text-green-500 mr-2">✓</span>
                  <span>$20k-50k per application (70-90% savings)</span>
                </li>
                <li className="flex items-start">
                  <span className="text-green-500 mr-2">✓</span>
                  <span>Built by clinicians for clinicians</span>
                </li>
                <li className="flex items-start">
                  <span className="text-green-500 mr-2">✓</span>
                  <span>Agent Team (3-5 specialized agents) + physician</span>
                </li>
                <li className="flex items-start">
                  <span className="text-green-500 mr-2">✓</span>
                  <span>Native EHR integration via MCP</span>
                </li>
              </ul>
            </div>
          </div>
        </motion.div>

        {/* Key Highlights */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
        >
          <h3 className="text-3xl font-bold text-sinai-navy mb-8 text-center">Why Agentic Development Works</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {highlights.map((highlight, index) => (
              <motion.div
                key={highlight.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: index * 0.1 }}
                className="bg-white rounded-xl shadow-lg p-6 hover:shadow-xl transition-shadow border border-gray-100"
              >
                <div className="w-12 h-12 bg-gradient-to-br from-sinai-cyan to-sinai-magenta rounded-lg flex items-center justify-center mb-4">
                  <highlight.icon className="w-6 h-6 text-white" />
                </div>
                <h4 className="text-lg font-bold text-sinai-navy mb-2">{highlight.title}</h4>
                <p className="text-gray-600">{highlight.description}</p>
              </motion.div>
            ))}
          </div>
        </motion.div>

        {/* Stats */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="mt-16 bg-gradient-to-r from-sinai-navy to-sinai-dark rounded-2xl p-12 text-white"
        >
          <h3 className="text-3xl font-bold mb-8 text-center">By The Numbers</h3>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
            <div className="text-center">
              <div className="text-4xl font-bold text-sinai-cyan mb-2">5+</div>
              <div className="text-sm text-gray-300">Production Applications</div>
            </div>
            <div className="text-center">
              <div className="text-4xl font-bold text-sinai-magenta mb-2">92%+</div>
              <div className="text-sm text-gray-300">AI-Assisted Code</div>
            </div>
            <div className="text-center">
              <div className="text-4xl font-bold text-sinai-cyan mb-2">$1.5M+</div>
              <div className="text-sm text-gray-300">Total Cost Savings</div>
            </div>
            <div className="text-center">
              <div className="text-4xl font-bold text-sinai-magenta mb-2">2-6</div>
              <div className="text-sm text-gray-300">Weeks to Deploy</div>
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  );
}
