import { motion } from 'framer-motion';
import { Sparkles, Code2, Stethoscope, Zap, Shield, TrendingUp } from 'lucide-react';

export function Overview() {
  const highlights = [
    {
      icon: Sparkles,
      title: 'AI-Powered Development',
      description: '83.8% of code generated by AI assistants, reviewed and refined by physician-developers'
    },
    {
      icon: Zap,
      title: 'Rapid Deployment',
      description: 'From clinical insight to production application in 4-8 weeks, not 6-12 months'
    },
    {
      icon: Shield,
      title: 'HIPAA Compliant',
      description: 'Security and privacy by design, meeting all healthcare regulatory requirements'
    },
    {
      icon: TrendingUp,
      title: 'Proven ROI',
      description: '$50k-200k annual savings per application vs traditional enterprise software'
    },
    {
      icon: Stethoscope,
      title: 'Clinician-Led',
      description: 'Built by physicians who understand workflows, pain points, and clinical needs'
    },
    {
      icon: Code2,
      title: 'Production Quality',
      description: 'Enterprise-grade applications with professional testing, monitoring, and support'
    }
  ];

  return (
    <section id="overview" className="py-20 bg-white scroll-mt-16">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header with Mount Sinai Logo */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <div className="flex justify-center mb-8">
            <img
              src="/mount-sinai-logo-production.png"
              alt="Mount Sinai Health System"
              className="h-20 w-auto"
            />
          </div>
          <h2 className="text-4xl md:text-5xl font-bold text-sinai-navy mb-4">
            The Agentic Laboratory
          </h2>
          <p className="text-xl text-gray-700 mb-2">
            Mount Sinai West Hospital
          </p>
          <p className="text-lg text-sinai-cyan font-semibold">
            Where Healthcare Meets Intelligent Software Development
          </p>
        </motion.div>

        {/* Mission Statement */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="max-w-4xl mx-auto mb-16"
        >
          <div className="bg-gradient-to-r from-sinai-cyan/10 to-sinai-magenta/10 rounded-2xl p-8 border-l-4 border-sinai-cyan">
            <h3 className="text-2xl font-bold text-sinai-navy mb-4">Breaking Down Every Barrier</h3>
            <p className="text-lg text-gray-700 leading-relaxed mb-4">
              For decades, brilliant clinical minds have been locked out of software creation by technical barriers. The Agentic Laboratory demolishes these walls entirely. Software agents with coding ability don't just assist development—they eliminate the barriers between clinical insight and software reality.
            </p>
            <p className="text-lg text-gray-700 leading-relaxed">
              When clinical expertise directly becomes software reality, innovation moves at the speed of insight, not implementation. The doctor who sees the problem can now build the solution. No translation phase. No gatekeepers. No barriers.
            </p>
          </div>
        </motion.div>

        {/* The Problem */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="mb-16"
        >
          <h3 className="text-3xl font-bold text-sinai-navy mb-8 text-center">The Traditional Barrier Stack vs. Barrier-Free Development</h3>
          <div className="grid md:grid-cols-2 gap-8">
            <div className="bg-red-50 rounded-2xl p-6 border-l-4 border-red-500">
              <h4 className="text-xl font-bold text-red-900 mb-3">Traditional Barriers</h4>
              <ul className="space-y-2 text-gray-700">
                <li className="flex items-start">
                  <span className="text-red-500 mr-2">🚧</span>
                  <span><strong>Technical Barrier:</strong> Brilliant doctors can't code their ideas</span>
                </li>
                <li className="flex items-start">
                  <span className="text-red-500 mr-2">🚧</span>
                  <span><strong>Translation Barrier:</strong> Clinical needs lost through intermediaries</span>
                </li>
                <li className="flex items-start">
                  <span className="text-red-500 mr-2">🚧</span>
                  <span><strong>Time Barrier:</strong> Months-long cycles kill innovation momentum</span>
                </li>
                <li className="flex items-start">
                  <span className="text-red-500 mr-2">🚧</span>
                  <span><strong>Cost Barrier:</strong> $200K enterprise solutions for $20K problems</span>
                </li>
                <li className="flex items-start">
                  <span className="text-red-500 mr-2">🚧</span>
                  <span><strong>Gatekeeper Barrier:</strong> IT departments become innovation bottlenecks</span>
                </li>
              </ul>
            </div>
            <div className="bg-green-50 rounded-2xl p-6 border-l-4 border-green-500">
              <h4 className="text-xl font-bold text-green-900 mb-3">Barriers Demolished</h4>
              <ul className="space-y-2 text-gray-700">
                <li className="flex items-start">
                  <span className="text-green-500 mr-2">💥</span>
                  <span><strong>Technical → Demolished:</strong> Clinicians build software directly with AI agents</span>
                </li>
                <li className="flex items-start">
                  <span className="text-green-500 mr-2">💥</span>
                  <span><strong>Translation → Eliminated:</strong> Medical language becomes code instantly</span>
                </li>
                <li className="flex items-start">
                  <span className="text-green-500 mr-2">💥</span>
                  <span><strong>Time → Dissolved:</strong> Ideas become reality the same day</span>
                </li>
                <li className="flex items-start">
                  <span className="text-green-500 mr-2">💥</span>
                  <span><strong>Cost → Shattered:</strong> $50K solutions replace $200K enterprise software</span>
                </li>
                <li className="flex items-start">
                  <span className="text-green-500 mr-2">💥</span>
                  <span><strong>Gatekeeping → Obliterated:</strong> Direct clinical insight to production code</span>
                </li>
              </ul>
            </div>
          </div>
        </motion.div>

        {/* Key Highlights */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
        >
          <h3 className="text-3xl font-bold text-sinai-navy mb-8 text-center">Why Agentic Development Works</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {highlights.map((highlight, index) => (
              <motion.div
                key={highlight.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: index * 0.1 }}
                className="bg-white rounded-xl shadow-lg p-6 hover:shadow-xl transition-shadow border border-gray-100"
              >
                <div className="w-12 h-12 bg-gradient-to-br from-sinai-cyan to-sinai-magenta rounded-lg flex items-center justify-center mb-4">
                  <highlight.icon className="w-6 h-6 text-white" />
                </div>
                <h4 className="text-lg font-bold text-sinai-navy mb-2">{highlight.title}</h4>
                <p className="text-gray-600">{highlight.description}</p>
              </motion.div>
            ))}
          </div>
        </motion.div>

        {/* Stats */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="mt-16 bg-gradient-to-r from-sinai-navy to-sinai-dark rounded-2xl p-12 text-white"
        >
          <h3 className="text-3xl font-bold mb-8 text-center">By The Numbers</h3>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
            <div className="text-center">
              <div className="text-4xl font-bold text-sinai-cyan mb-2">5</div>
              <div className="text-sm text-gray-300">Production Applications</div>
            </div>
            <div className="text-center">
              <div className="text-4xl font-bold text-sinai-magenta mb-2">83.8%</div>
              <div className="text-sm text-gray-300">AI Code Generation</div>
            </div>
            <div className="text-center">
              <div className="text-4xl font-bold text-sinai-cyan mb-2">$1M+</div>
              <div className="text-sm text-gray-300">Total Cost Savings</div>
            </div>
            <div className="text-center">
              <div className="text-4xl font-bold text-sinai-magenta mb-2">4-8</div>
              <div className="text-sm text-gray-300">Weeks to Deploy</div>
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  );
}
