import { motion } from 'framer-motion';
import { Sparkles, Code2, Stethoscope, Zap, Shield, TrendingUp } from 'lucide-react';

export function Overview() {
  const highlights = [
    {
      icon: Sparkles,
      title: 'AI-Powered Development',
      description: '83.8% of code generated by AI assistants, reviewed and refined by physician-developers'
    },
    {
      icon: Zap,
      title: 'Rapid Deployment',
      description: 'From clinical insight to production application in 4-8 weeks, not 6-12 months'
    },
    {
      icon: Shield,
      title: 'HIPAA Compliant',
      description: 'Security and privacy by design, meeting all healthcare regulatory requirements'
    },
    {
      icon: TrendingUp,
      title: 'Proven ROI',
      description: '$50k-200k annual savings per application vs traditional enterprise software'
    },
    {
      icon: Stethoscope,
      title: 'Clinician-Led',
      description: 'Built by physicians who understand workflows, pain points, and clinical needs'
    },
    {
      icon: Code2,
      title: 'Production Quality',
      description: 'Enterprise-grade applications with professional testing, monitoring, and support'
    }
  ];

  return (
    <section id="overview" className="py-20 bg-white scroll-mt-16">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header with Mount Sinai Logo */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <div className="flex justify-center mb-8">
            <img
              src="/mount-sinai-logo-production.png"
              alt="Mount Sinai Health System"
              className="h-20 w-auto"
            />
          </div>
          <h2 className="text-4xl md:text-5xl font-bold text-sinai-navy mb-4">
            The Agentic Laboratory
          </h2>
          <p className="text-xl text-gray-700 mb-2">
            Mount Sinai West Hospital
          </p>
          <p className="text-lg text-sinai-cyan font-semibold">
            Where Healthcare Meets Intelligent Software Development
          </p>
        </motion.div>

        {/* Mission Statement */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="max-w-4xl mx-auto mb-16"
        >
          <div className="bg-gradient-to-r from-sinai-cyan/10 to-sinai-magenta/10 rounded-2xl p-8 border-l-4 border-sinai-cyan">
            <h3 className="text-2xl font-bold text-sinai-navy mb-4">Our Mission</h3>
            <p className="text-lg text-gray-700 leading-relaxed mb-4">
              The Agentic Laboratory represents a paradigm shift in healthcare software development. We empower physicians and clinical staff to build their own production-grade applications using AI-assisted development, dramatically reducing cost and time-to-market while ensuring solutions perfectly match clinical workflows.
            </p>
            <p className="text-lg text-gray-700 leading-relaxed">
              Instead of waiting months for IT departments or spending hundreds of thousands on enterprise software, our physician-developers create custom solutions in weeks—with 83.8% of code generated by AI and 100% clinical relevance.
            </p>
          </div>
        </motion.div>

        {/* The Problem */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="mb-16"
        >
          <h3 className="text-3xl font-bold text-sinai-navy mb-8 text-center">The Healthcare Software Problem</h3>
          <div className="grid md:grid-cols-2 gap-8">
            <div className="bg-red-50 rounded-2xl p-6 border-l-4 border-red-500">
              <h4 className="text-xl font-bold text-red-900 mb-3">Traditional Approach</h4>
              <ul className="space-y-2 text-gray-700">
                <li className="flex items-start">
                  <span className="text-red-500 mr-2">✗</span>
                  <span>6-12 month development cycles</span>
                </li>
                <li className="flex items-start">
                  <span className="text-red-500 mr-2">✗</span>
                  <span>$200k-500k+ per application</span>
                </li>
                <li className="flex items-start">
                  <span className="text-red-500 mr-2">✗</span>
                  <span>Misaligned with clinical workflows</span>
                </li>
                <li className="flex items-start">
                  <span className="text-red-500 mr-2">✗</span>
                  <span>Requires large IT teams</span>
                </li>
                <li className="flex items-start">
                  <span className="text-red-500 mr-2">✗</span>
                  <span>Slow to adapt to changing needs</span>
                </li>
              </ul>
            </div>
            <div className="bg-green-50 rounded-2xl p-6 border-l-4 border-green-500">
              <h4 className="text-xl font-bold text-green-900 mb-3">Agentic Laboratory</h4>
              <ul className="space-y-2 text-gray-700">
                <li className="flex items-start">
                  <span className="text-green-500 mr-2">✓</span>
                  <span>4-8 week development cycles</span>
                </li>
                <li className="flex items-start">
                  <span className="text-green-500 mr-2">✓</span>
                  <span>$20k-50k per application (70-90% savings)</span>
                </li>
                <li className="flex items-start">
                  <span className="text-green-500 mr-2">✓</span>
                  <span>Built by clinicians for clinicians</span>
                </li>
                <li className="flex items-start">
                  <span className="text-green-500 mr-2">✓</span>
                  <span>Single physician-developer + AI</span>
                </li>
                <li className="flex items-start">
                  <span className="text-green-500 mr-2">✓</span>
                  <span>Rapid iteration and updates</span>
                </li>
              </ul>
            </div>
          </div>
        </motion.div>

        {/* Key Highlights */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
        >
          <h3 className="text-3xl font-bold text-sinai-navy mb-8 text-center">Why Agentic Development Works</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {highlights.map((highlight, index) => (
              <motion.div
                key={highlight.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: index * 0.1 }}
                className="bg-white rounded-xl shadow-lg p-6 hover:shadow-xl transition-shadow border border-gray-100"
              >
                <div className="w-12 h-12 bg-gradient-to-br from-sinai-cyan to-sinai-magenta rounded-lg flex items-center justify-center mb-4">
                  <highlight.icon className="w-6 h-6 text-white" />
                </div>
                <h4 className="text-lg font-bold text-sinai-navy mb-2">{highlight.title}</h4>
                <p className="text-gray-600">{highlight.description}</p>
              </motion.div>
            ))}
          </div>
        </motion.div>

        {/* Stats */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="mt-16 bg-gradient-to-r from-sinai-navy to-sinai-dark rounded-2xl p-12 text-white"
        >
          <h3 className="text-3xl font-bold mb-8 text-center">By The Numbers</h3>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
            <div className="text-center">
              <div className="text-4xl font-bold text-sinai-cyan mb-2">5</div>
              <div className="text-sm text-gray-300">Production Applications</div>
            </div>
            <div className="text-center">
              <div className="text-4xl font-bold text-sinai-magenta mb-2">83.8%</div>
              <div className="text-sm text-gray-300">AI Code Generation</div>
            </div>
            <div className="text-center">
              <div className="text-4xl font-bold text-sinai-cyan mb-2">$1M+</div>
              <div className="text-sm text-gray-300">Total Cost Savings</div>
            </div>
            <div className="text-center">
              <div className="text-4xl font-bold text-sinai-magenta mb-2">4-8</div>
              <div className="text-sm text-gray-300">Weeks to Deploy</div>
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  );
}
